import { type Edge } from '@xyflow/react';

export const initialEdges: Edge[] = [
  {
    id: 'id1-id2',
    source: '1',
    target: '2',
    type: 'straight',
    // label: 'working',
    // markerEnd: {
    //   type: MarkerType.ArrowClosed,
    // },
  },
  {
    id: 'id2-id3',
    source: '2',
    target: '3',
    type: 'straight',
    // label: 'working',
    // markerEnd: {
    //   type: MarkerType.ArrowClosed,
    // },
  },
  {
    id: 'id3-id4',
    source: '3',
    target: '4',
    type: 'straight',
    // markerEnd: {
    //   type: MarkerType.ArrowClosed,
    // },
  },
  {
    id: 'id4-id5',
    source: '4',
    target: '5',
    type: 'straight',
    // markerEnd: {
    //   type: MarkerType.ArrowClosed,
    // },
  },
  {
    id: 'id5-id6',
    source: '5',
    target: '6',
    type: 'straight',
    label: 'For master projects',

    labelBgPadding: [10, 0],
    // markerEnd: {
    //   type: MarkerType.ArrowClosed,
    // },
  },
  {
    id: 'id6-id7',
    source: '6',
    target: '7',
    type: 'straight',
    // markerEnd: {
    //   type: MarkerType.ArrowClosed,
    // },
  },
  {
    id: 'id5-id7',
    source: '5',
    target: '7',
    sourceHandle: 'bottom',
    targetHandle: 'bottom',
    type: 'smoothstep',
    label: 'For high rise',
    // labelBgStyle: {
    //   fill: '#f2f3fa',
    // },
    labelBgPadding: [10, 0],
    // markerEnd: {
    //   type: MarkerType.ArrowClosed,
    // },
  },
  {
    id: 'id7-id8',
    source: '7',
    target: '8',
    type: 'bezier',
    animated: true,
    // markerEnd: {
    //   type: MarkerType.ArrowClosed,
    // },
  },
  {
    id: 'id8-id10',
    source: '8',
    target: '10',
    sourceHandle: 'right',
    type: 'smoothstep',
    // animated: true,
    // markerEnd: {
    //   type: MarkerType.ArrowClosed,
    // },
  },
  {
    id: 'id8-id11',
    source: '8',
    target: '11',
    sourceHandle: 'right',
    type: 'smoothstep',
  },
  {
    id: 'id10-id12',
    source: '10',
    target: '12',
    // sourceHandle: 'right',
    type: 'stright',
  },
  {
    id: 'id12-id15',
    source: '12',
    target: '15',
    // sourceHandle: 'bottom',
    // targetHandle: 'top',
    type: 'smoothstep',
  },
  {
    id: 'id12-id16',
    source: '12',
    target: '16',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'smoothstep',
  },
  {
    id: 'id16-id17',
    source: '16',
    target: '17',
    // sourceHandle: 'bottom',
    // targetHandle: 'top',
    type: 'smoothstep',
  },
  {
    id: 'id17-id18',
    source: '17',
    target: '18',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id18-id19',
    source: '18',
    target: '19',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id19-id20',
    source: '19',
    target: '20',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id20-id21',
    source: '20',
    target: '21',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id21-id22',
    source: '21',
    target: '22',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id8-id13',
    source: '8',
    target: '13',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'smoothstep',
  },
  {
    id: 'id11-id14',
    source: '11',
    target: '14',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id11-id23',
    source: '11',
    target: '23',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id17-id34',
    source: '17',
    target: '34',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'smoothstep',
  },
  {
    id: 'id34-id24',
    source: '34',
    target: '24',
    sourceHandle: 'right',
    targetHandle: 'bottom',
    type: 'smoothstep',
  },
  {
    id: 'id24-id17',
    source: '24',
    target: '17',
    // sourceHandle: 'top',
    // targetHandle: 'right',
    type: 'smoothstep',
  },
  {
    id: 'id19-id18',
    source: '19',
    target: '18',
    targetHandle: 'left',
    sourceHandle: 'bottom',
    type: 'smoothstep',
    label: 'REJECTED',
    // labelBgStyle: {
    //   fill: '#f2f3fa',
    // },
    labelBgPadding: [10, 0],
  },
  {
    id: 'id21-id23',
    source: '21',
    target: '23',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'stright',
    // animated: true,
  },
  {
    id: 'id23-id30',
    source: '23',
    target: '30',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id22-id30',
    source: '22',
    target: '30',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id22-id63',
    source: '22',
    target: '63',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'smoothstep',
  },
  // {
  //   id: 'id27-id28',
  //   source: '27',
  //   target: '28',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id28-id29',
  //   source: '28',
  //   target: '29',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id30-id31',
  //   source: '30',
  //   target: '31',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id31-id32',
  //   source: '31',
  //   target: '32',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  //   label: 'APPROVED',
  //   labelBgStyle: {
  //     fill: '#f2f3fa',
  //   },
  //   labelBgPadding: [10, 0],
  // },
  // {
  //   id: 'id32-id33',
  //   source: '32',
  //   target: '33',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id33-id34',
  //   source: '33',
  //   target: '34',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id34-id29',
  //   source: '34',
  //   target: '29',
  //   sourceHandle: 'right',
  //   targetHandle: 'bottom',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id35-id35A',
  //   source: '35',
  //   target: '35A',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id35A-id35B',
  //   source: '35A',
  //   target: '35B',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id35B-id36',
  //   source: '35B',
  //   target: '36',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id36-id37',
  //   source: '36',
  //   target: '37',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'top',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id37-id38',
  //   source: '37',
  //   target: '38',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id38-id39',
  //   source: '38',
  //   target: '39',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  {
    id: 'id7-id31',
    source: '7',
    target: '31',
    type: 'bezier',
    animated: true,
  },
  {
    id: 'id7-id36',
    source: '7',
    target: '36',
    type: 'bezier',
    animated: true,
  },
  {
    id: 'id7-id40',
    source: '7',
    target: '40',
    type: 'bezier',
    animated: true,
  },
  {
    id: 'id7-id25',
    source: '7',
    target: '25',
    type: 'bezier',
    animated: true,
  },
  {
    id: 'id13-id54',
    source: '13',
    target: '54',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id25-id26',
    source: '25',
    target: '26',
    // sourceHandle: 'bottom',
    // targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id26-id27',
    source: '26',
    target: '27',
    // sourceHandle: 'bottom',
    // targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id27-id28',
    source: '27',
    target: '28',
    // sourceHandle: 'right',
    // targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id28-id29',
    source: '28',
    target: '29',
    // sourceHandle: 'right',
    // targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id29-id30',
    source: '29',
    target: '30',
    // sourceHandle: 'right',
    // targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id31-id32',
    source: '31',
    target: '32',
    // sourceHandle: 'right',
    // targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id32-id31',
    source: '32',
    target: '31',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'smoothstep',
    label: 'REJECTED',
    // labelBgStyle: {
    //   fill: '#f2f3fa',
    // },
    labelBgPadding: [10, 0],
  },
  {
    id: 'id32-id33',
    source: '32',
    target: '33',
    // sourceHandle: 'right',
    // targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id33-id32',
    source: '33',
    target: '32',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'smoothstep',
    label: 'REJECTED',
    // labelBgStyle: {
    //   fill: '#f2f3fa',
    // },
    labelBgPadding: [10, 0],
  },
  {
    id: 'id33-id34',
    source: '33',
    target: '34',
    // sourceHandle: 'right',
    // targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id34-id35',
    source: '34',
    target: '35',
    // sourceHandle: 'right',
    // targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id35-id30',
    source: '35',
    target: '30',
    sourceHandle: 'right',
    targetHandle: 'bottom',
    type: 'smoothstep',
  },
  {
    id: 'id36-id37',
    source: '36',
    target: '37',
    // sourceHandle: 'right',
    // targetHandle: 'bottom',
    type: 'smoothstep',
  },
  {
    id: 'id37-id38',
    source: '37',
    target: '38',
    // sourceHandle: 'right',
    // targetHandle: 'bottom',
    type: 'smoothstep',
  },
  {
    id: 'id38-id39',
    source: '38',
    target: '39',
    // sourceHandle: 'right',
    // targetHandle: 'bottom',
    type: 'smoothstep',
  },
  {
    id: 'id39-id40',
    source: '39',
    target: '40',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'smoothstep',
  },
  {
    id: 'id40-id41',
    source: '40',
    target: '41',
    type: 'smoothstep',
  },
  {
    id: 'id41-id42',
    source: '41',
    target: '42',
    type: 'smoothstep',
  },
  {
    id: 'id42-id70',
    source: '42',
    target: '70',
    type: 'stright',
  },
  {
    id: 'id42-id43',
    source: '42',
    target: '43',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'smoothstep',
  },
  {
    id: 'id43-id44',
    source: '42',
    target: '44',
    // sourceHandle: 'bottom',
    // targetHandle: 'top',
    type: 'smoothstep',
  },
  {
    id: 'id43-id45',
    source: '43',
    target: '45',
    type: 'smoothstep',
  },
  {
    id: 'id45-id46',
    source: '45',
    target: '46',
    type: 'smoothstep',
  },
  {
    id: 'id46-id47',
    source: '46',
    target: '47',
    type: 'smoothstep',
  },
  {
    id: 'id47-id48',
    source: '47',
    target: '48',
    type: 'smoothstep',
  },
  {
    id: 'id48-id49',
    source: '48',
    target: '49',
    type: 'smoothstep',
  },
  {
    id: 'id49-id50',
    source: '49',
    target: '50',
    type: 'smoothstep',
  },
  {
    id: 'id49-id51',
    source: '49',
    target: '51',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id50-id52',
    source: '50',
    target: '52',
    type: 'smoothstep',
  },
  {
    id: 'id50-id53',
    source: '50',
    target: '53',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id36-id54',
    source: '36',
    target: '54',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id54-id55',
    source: '54',
    target: '55',
    type: 'smoothstep',
  },
  {
    id: 'id55-id59',
    source: '55',
    target: '59',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id55-id56',
    source: '55',
    target: '56',
    type: 'smoothstep',
  },
  {
    id: 'id56-id57',
    source: '56',
    target: '57',
    type: 'smoothstep',
  },
  {
    id: 'id57-id58',
    source: '57',
    target: '58',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id57-id53',
    source: '57',
    target: '53',
    sourceHandle: 'right',
    targetHandle: 'bottom',
    type: 'smoothstep',
  },
  {
    id: 'id53-id83',
    source: '53',
    target: '83',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id55-id60',
    source: '55',
    target: '60',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'smoothstep',
  },
  {
    id: 'id60-id61',
    source: '60',
    target: '61',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id60-id62',
    source: '60',
    target: '62',
    type: 'smoothstep',
  },
  {
    id: 'id62-id83',
    source: '62',
    target: '83',
    sourceHandle: 'right',
    targetHandle: 'bottom',
    type: 'smoothstep',
  },
  {
    id: 'id63-id64',
    source: '63',
    target: '64',
    type: 'smoothstep',
  },
  {
    id: 'id64-id65',
    source: '64',
    target: '65',
    sourceHandle: 'right',
    targetHandle: 'bottom',
    type: 'smoothstep',
  },
  {
    id: 'id64-id66',
    source: '64',
    target: '66',
    type: 'smoothstep',
  },
  {
    id: 'id66-id64',
    source: '66',
    target: '64',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'smoothstep',
    label: 'REJECTED',

    labelBgPadding: [10, 0],
  },
  {
    id: 'id66-id67',
    source: '66',
    target: '67',
    type: 'smoothstep',
  },
  {
    id: 'id67-id68',
    source: '67',
    target: '68',
    sourceHandle: 'right',
    targetHandle: 'bottom',
    type: 'smoothstep',
  },
  {
    id: 'id67-id69',
    source: '67',
    target: '69',
    // sourceHandle: 'right',
    type: 'smoothstep',
  },
  {
    id: 'id69-id82',
    source: '69',
    target: '82',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'smoothstep',
  },
  {
    id: 'id70-id71',
    source: '70',
    target: '71',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id70-id72',
    source: '70',
    target: '72',
    type: 'smoothstep',
  },
  {
    id: 'id71-id73',
    source: '71',
    target: '73',
    type: 'smoothstep',
  },
  {
    id: 'id73-id74',
    source: '73',
    target: '74',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'smoothstep',
  },
  {
    id: 'id74-id75',
    source: '74',
    target: '75',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id74-id76',
    source: '74',
    target: '76',
    type: 'smoothstep',
  },
  {
    id: 'id76-id77',
    source: '76',
    target: '77',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
  },
  {
    id: 'id76-id78',
    source: '76',
    target: '78',
    type: 'smoothstep',
  },
  {
    id: 'id78-id76',
    source: '78',
    target: '76',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'smoothstep',
    label: 'REJECTED',
    // labelBgStyle: {
    //   fill: '#f2f3fa',
    // },
    labelBgPadding: [10, 0],
  },
  {
    id: 'id78-id79',
    source: '78',
    target: '79',
    type: 'smoothstep',
  },
  {
    id: 'id79-id76',
    source: '79',
    target: '76',
    sourceHandle: 'bottom',
    targetHandle: 'left',
    type: 'smoothstep',
    label: 'REJECTED',
    // labelBgStyle: {
    //   fill: '#f2f3fa',
    // },
    labelBgPadding: [10, 0],
  },
  {
    id: 'id79-id80',
    source: '79',
    target: '80',
    type: 'smoothstep',
  },
  {
    id: 'id80-id81',
    source: '80',
    target: '81',
    sourceHandle: 'bottom',
    targetHandle: 'top',
    type: 'stright',
  },
  {
    id: 'id80-id82',
    source: '80',
    target: '82',
    type: 'smoothstep',
  },
  // {
  //   id: 'id39-id40',
  //   source: '39',
  //   target: '40',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'left',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id40-id41',
  //   source: '40',
  //   target: '41',
  //   // sourceHandle: 'left',
  //   // targetHandle: 'right',
  //   type: 'stright',
  // },
  // {
  //   id: 'id41-id42',
  //   source: '41',
  //   target: '42',
  //   // sourceHandle: 'left',
  //   // targetHandle: 'right',
  //   type: 'stright',
  // },
  // {
  //   id: 'id42-id42A',
  //   source: '42',
  //   target: '42A',
  //   // sourceHandle: 'left',
  //   // targetHandle: 'right',
  //   type: 'stright',
  // },
  // {
  //   id: 'id42A-id42B',
  //   source: '42A',
  //   target: '42B',
  //   // sourceHandle: 'left',
  //   // targetHandle: 'right',
  //   type: 'stright',
  // },
  // {
  //   id: 'id42-id43',
  //   source: '42',
  //   target: '43',
  //   // sourceHandle: 'left',
  //   // targetHandle: 'right',
  //   type: 'stright',
  // },
  // {
  //   id: 'id43-id44',
  //   source: '43',
  //   target: '44',
  //   // sourceHandle: 'left',
  //   // targetHandle: 'right',
  //   type: 'stright',
  // },
  // {
  //   id: 'id43-id45',
  //   source: '43',
  //   target: '45',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'top',
  //   type: 'stright',
  // },
  // {
  //   id: 'id44-id46',
  //   source: '44',
  //   target: '46',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id44-id47',
  //   source: '44',
  //   target: '47',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'top',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id48-id49',
  //   source: '48',
  //   target: '49',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id49-id50',
  //   source: '49',
  //   target: '50',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id50-id47',
  //   source: '50',
  //   target: '47',
  //   sourceHandle: 'right',
  //   targetHandle: 'bottom',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id50-id41',
  //   source: '50',
  //   target: '51',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'top',
  //   type: 'stright',
  // },
  // {
  //   id: 'id49-id52',
  //   source: '49',
  //   target: '52',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'top',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id49-id53',
  //   source: '49',
  //   target: '53',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id53-id54',
  //   source: '53',
  //   target: '54',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'top',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id53-id55',
  //   source: '53',
  //   target: '55',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id35-id48',
  //   source: '35',
  //   target: '48',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'left',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id7-id48',
  //   source: '7',
  //   target: '48',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'left',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id56-id57',
  //   source: '56',
  //   target: '57',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id57-id58',
  //   source: '57',
  //   target: '58',
  //   sourceHandle: 'right',
  //   targetHandle: 'bottom',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id57-id59',
  //   source: '57',
  //   target: '59',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id59-id57',
  //   source: '59',
  //   target: '57',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'left',
  //   type: 'smoothstep',
  //   label: 'REJECTED',
  //   labelBgStyle: {
  //     fill: '#f2f3fa',
  //   },
  //   labelBgPadding: [10, 0],
  // },
  // {
  //   id: 'id59-id60',
  //   source: '59',
  //   target: '60',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  //   label: 'APPROVED',
  //   labelBgStyle: {
  //     fill: '#f2f3fa',
  //   },
  //   labelBgPadding: [10, 0],
  // },
  // {
  //   id: 'id60-id61',
  //   source: '60',
  //   target: '61',
  //   sourceHandle: 'right',
  //   targetHandle: 'bottom',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id60-id62',
  //   source: '60',
  //   target: '62',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id62-id76',
  //   source: '62',
  //   target: '75',
  //   sourceHandle: 'right',
  //   targetHandle: 'top',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id39-id63',
  //   source: '39',
  //   target: '63',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id63-id65',
  //   source: '63',
  //   target: '65',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id63-id64',
  //   source: '63',
  //   target: '64',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id64-id66',
  //   source: '64',
  //   target: '66',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id66-id67',
  //   source: '66',
  //   target: '67',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id67-id69',
  //   source: '67',
  //   target: '69',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id69-id70',
  //   source: '69',
  //   target: '70',
  //   sourceHandle: 'right',
  //   targetHandle: 'bottom',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id69-id71',
  //   source: '69',
  //   target: '71',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  //   // label: 'REJECTED',
  //   // labelBgStyle: {
  //   //   fill: '#f2f3fa',
  //   // },
  //   labelBgPadding: [10, 0],
  // },
  // {
  //   id: 'id71-id69',
  //   source: '71',
  //   target: '69',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'left',
  //   type: 'smoothstep',
  //   label: 'REJECTED',
  //   labelBgStyle: {
  //     fill: '#f2f3fa',
  //   },
  //   labelBgPadding: [10, 0],
  // },
  // {
  //   id: 'id72-id69',
  //   source: '72',
  //   target: '69',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'left',
  //   type: 'smoothstep',
  //   label: 'REJECTED',
  //   labelBgStyle: {
  //     fill: '#f2f3fa',
  //   },
  //   labelBgPadding: [10, 0],
  // },
  // {
  //   id: 'id71-id72',
  //   source: '71',
  //   target: '72',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id72-id73',
  //   source: '72',
  //   target: '73',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id73-id74',
  //   source: '73',
  //   target: '74',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'top',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id73-id75',
  //   source: '73',
  //   target: '75',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'smoothstep',
  // },
  // {
  //   id: 'id67-id68',
  //   source: '67',
  //   target: '68',
  //   sourceHandle: 'bottom',
  //   targetHandle: 'top',
  //   type: 'stright',
  // },
  // {
  //   id: 'id47-id76',
  //   source: '47',
  //   target: '76',
  //   sourceHandle: 'right',
  //   targetHandle: 'left',
  //   type: 'stright',
  // },
  // {
  //   id: 'id55-id76',
  //   source: '55',
  //   target: '76',
  //   sourceHandle: 'right',
  //   targetHandle: 'bottom',
  //   type: 'smoothstep',
  // },
  {
    id: 'id82-id83',
    source: '82',
    target: '83',
    sourceHandle: 'right',
    targetHandle: 'top',
    type: 'smoothstep',
  },
];
