// import type { Node } from '@xyflow/react';
import { Mail, PersonStanding, Settings } from 'lucide-react';

export const initialNodes: any = [
  {
    id: 'InfoBlock',
    type: 'InfoBlock',
    // position: { x: 7500, y: 250 },
    data: {},
    draggable: false,
    selectable: false,
    focusable: false,
  },
  {
    id: 'IP',
    type: 'GroupNode',
    // position: { x: 1100, y: -550 },
    data: {
      label: 'Inventory & Pricing Readiness',
      height: '1050',
      width: '4000',
      bgColor: 'bg-indigo-100',
      borderColor: 'border-indigo-300',

      // width: 2200,
      // height: 300,
    },
    draggable: false,
    selectable: false,
    focusable: false,
    style: {
      zIndex: -1,
    },
  },
  {
    id: 'BR',
    type: 'GroupNode',
    // position: { x: 4350, y: 300 },
    data: {
      label: 'Booking Readiness',
      height: '1250',
      width: '3500',
      bgColor: 'bg-mist-200',
      borderColor: 'border-mist-300',
      // IconColor: 'text-yellow-600',
      // width: 2200,
      // height: 300,
    },
    draggable: false,
    selectable: false,
    focusable: false,
    style: {
      zIndex: -1,
    },
  },
  {
    id: 'FR',
    type: 'GroupNode',
    // position: { x: 1050, y: 1100 },
    data: {
      label: 'Financial Readiness',
      height: '1350',
      width: '2500',
      bgColor: 'bg-mauve-200',
      borderColor: 'border-mauve-300',
      // width: 2200,
      // height: 300,
    },
    draggable: false,
    selectable: false,
    focusable: false,
    style: {
      zIndex: -1,
    },
  },
  {
    id: '1',

    data: {
      label: 'MDO',
      text: 'Initiate Tracker, Select theCluster ID, Cluster Name &Provide Marketing Name,Launch Date',
      department: null,
      color: 'bg-blue-300',
      borderColor: 'border-blue-600',
      StepNumber: '1',
      Icon: PersonStanding,
    },

    type: 'rectangle',
  },
  {
    id: '2',
    // position: { x: -750, y: 495 },
    data: {
      label: 'DEVELOPMENT & CONCEPT',
      text: 'Uploads F&A ACC and Provide Project Details',
      department: null,
      color: 'bg-blue-300',
      borderColor: 'border-blue-600',
      StepNumber: '2',
      Icon: PersonStanding,
    },

    type: 'rectangle',
  },
  {
    id: '3',
    // position: { x: -350, y: 475 },
    data: {
      label: 'DESIGN & CONCEPT HOD',
      text: 'Approval',
      deparment: null,
      color: 'bg-blue-300',
      borderColor: 'border-blue-600',
      StepNumber: '3',
      Icon: Mail,
      IconColor: 'text-blue-600',
    },
    type: 'diamond',
  },
  {
    id: '4',
    // position: { x: -100, y: 475 },
    data: {
      label: 'BUDGETING HOD',
      text: 'Approval',
      deparment: null,
      color: 'bg-blue-300',
      StepNumber: '4',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'diamond',
  },
  {
    id: '5',
    // position: { x: 150, y: 475 },
    data: {
      label: 'Topology Based',
      text: 'Approval',
      deparment: null,
      // color: 'bg-blue-300',
      borderColor: 'border-blue-600',
    },
    type: 'diamond',
  },
  {
    id: '6',
    // position: { x: 500, y: 475 },
    data: {
      label: 'Technical Design HOD',
      text: 'Approval',
      deparment: null,
      color: 'bg-blue-300',
      StepNumber: '5',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'diamond',
  },
  {
    id: '7',
    // position: { x: 800, y: 475 },

    data: {
      label: 'Parallel Task',
      borderColor: 'border-gray-600',
      border: true,
    },
    type: 'circle',
  },
  {
    id: '8',
    // position: { x: 1400, y: -200 },
    data: {
      label: 'TECHNICAL DESIGN',
      text: 'Upload documents & Consultant letter',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      department: 'planning',
    },
    type: 'rectangle',
  },

  {
    id: '9',
    // position: { x: 1180, y: -300 },
    data: {
      label: 'SALESFORCE',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      text: 'Create the property ID & Location ID using API',
      department: 'planning',
    },
    type: 'rectangle',
  },
  {
    id: '10',
    // position: { x: 1680, y: -380 },
    data: {
      label: 'TECHNICAL VERIFIER',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      text: 'Approval',
      department: 'planning',
    },
    type: 'diamond',
  },
  {
    id: '11',
    // position: { x: 1680, y: -10 },
    data: {
      label: 'SALES ADMIN',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      text: 'Approval',
      department: 'planning',
    },
    type: 'diamond',
  },
  {
    id: '12',
    // position: { x: 2000, y: -380 },
    data: {
      label: 'SALES ADMIN',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      text: 'Approval',
      department: 'planning',
    },
    type: 'diamond',
  },
  {
    id: '13',
    // position: { x: 1400, y: 200 },
    data: {
      label: 'Consultant Letter Upload Tasks ends',
      color: 'bg-blue-200',
      text: 'Approval',
      department: 'planning',
      StepNumber: '6',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'circle',
  },
  {
    id: '14',
    // position: { x: 1680, y: 200 },
    data: {
      label: 'Layout & Unit plan upload',
      color: 'bg-blue-200',
      text: 'Task Ends',
      department: 'planning',
      StepNumber: '8',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'circle',
  },
  {
    id: '15',
    // position: { x: 2250, y: -380 },
    data: {
      label: 'Inventory Upload',
      color: 'bg-blue-200',
      text: 'Task Ends',
      department: 'planning',
      StepNumber: '7',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'circle',
  },
  {
    id: '16',
    // position: { x: 1960, y: -180 },
    data: {
      label: 'SALES OPS PRICING',
      color: 'bg-blue-200',
      text: 'Validate DocumentUpload & mark taskas completed',
      department: 'planning',
      StepNumber: '9',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '17',
    // position: { x: 2260, y: -180 },
    data: {
      label: 'Inventory live in',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      text: 'SALESFORCE',
      department: 'planning',
      StepNumber: '10',
    },
    type: 'rectangle',
  },
  {
    id: '18',
    // position: { x: 2560, y: -180 },
    data: {
      label: 'SALES OPS PRICING',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      text: 'Calculate pricing & Create payment plan',
      department: 'planning',
    },
    type: 'rectangle',
  },
  {
    id: '19',
    // position: { x: 2850, y: -200 },
    data: {
      label: 'CHAIRMAN',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      text: 'IOM Approval',
      department: 'planning',
    },
    type: 'diamond',
  },
  {
    id: '20',
    // position: { x: 3060, y: -180 },
    data: {
      label: 'SALES OPs',
      color: 'bg-blue-200',
      text: 'Mark Pricing and Payment Plan approval as Complete in Pega',
      department: 'planning',
      StepNumber: '13',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '21',
    // position: { x: 3300, y: -180 },
    data: {
      label: 'SALES ADMIN',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      text: 'Upload Pricing Validates it & TagPayment plan for each unit',
      department: 'planning',
    },
    type: 'rectangle',
  },
  {
    id: '22',
    // position: { x: 3560, y: -180 },
    data: {
      label: 'MIS HOD',
      color: 'bg-blue-200',
      text: 'Validates the pricing uploaded in Salesforce& Marks the Pega taskcomplete via Email',
      department: 'planning',
      StepNumber: '15',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '23',
    // position: { x: 3330, y: -10 },
    data: {
      label: 'Upload Pricing task Ends',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '14',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'circle',
  },
  {
    id: '24',
    // position: { x: 2700, y: 180 },
    data: {
      label: 'Add Sync back to Salesforce',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '12',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'circle',
  },
  {
    id: '25',
    // position: { x: 1500, y: 370 },
    data: {
      label: 'MARKETING',
      text: 'Enter their Estimated Completion Date',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '16',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '26',
    // position: { x: 1750, y: 370 },
    data: {
      label: 'MARKETING',
      text: 'Mark the completion of Marketing Material Readiness',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '17',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '27',
    // position: { x: 2000, y: 370 },
    data: {
      label: 'DIGITAL MARKETING',
      text: 'Creative Adaptation Preparation',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '18',
      Icon: PersonStanding,
      borderColor: 'border-blue-600',
    },
    type: 'rectangle',
  },
  {
    id: '28',
    // position: { x: 2800, y: 380 },
    data: {
      label: 'CREATIVE HEAD',
      text: 'Approval of Adaptations',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '19',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '29',
    // position: { x: 3050, y: 380 },
    data: {
      label: 'DIGITAL MARKETING',
      text: 'Campaign Execution',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '20',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '30',
    // position: { x: 3600, y: 370 },
    data: {
      label: 'Marketing Launch Ready',
      // text: 'Campaign Execution',
      color: 'bg-orange-400',
      borderColor: 'border-orange-600',

      department: 'planning',
    },
    type: 'circle',
  },
  {
    id: '31',
    // position: { x: 1500, y: 570 },
    data: {
      label: 'CENTRAL PLANNING',
      text: 'Calculate ACD',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      department: 'planning',
    },
    type: 'rectangle',
  },
  {
    id: '32',
    // position: { x: 1900, y: 550 },
    data: {
      label: 'HOD',
      text: 'Approval',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      department: 'planning',
    },
    type: 'diamond',
  },
  {
    id: '33',
    // position: { x: 2300, y: 550 },
    data: {
      label: 'CPO ',
      text: 'Approval',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      department: 'planning',
    },
    type: 'diamond',
  },
  {
    id: '34',
    // position: { x: 2500, y: 570 },
    data: {
      label: 'Upload ACD to PM Web ',
      // text: 'Approval',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      department: 'planning',
    },
    type: 'rectangle',
  },
  {
    id: '35',
    // position: { x: 3000, y: 570 },
    data: {
      label: 'PEGA validates the PM Web Upload and auto Close the task',
      // text: 'Approval',
      color: 'bg-blue-200',
      // department: 'planning',
      StepNumber: '11',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'rectangle',
  },
  {
    id: '36',
    // position: { x: 1500, y: 750 },
    data: {
      label: 'TREASURY',
      text: 'Open Corporate Bank Account and mark task as complete',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '21',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '37',
    // position: { x: 1850, y: 750 },
    data: {
      label: 'TREASURY',
      text: 'Raise a SR ticketfor Finance APP team to configure Corporate Bankaccount in Fusion',
      color: 'bg-green-100',
      department: 'planning',
      StepNumber: '22',
      Icon: Mail,
      borderColor: 'border-green-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '38',
    // position: { x: 2200, y: 750 },
    data: {
      label: 'Finance App',
      text: 'Configure Corporate Bank Account in Fusion',
      color: 'bg-green-100',
      department: 'planning',
      StepNumber: '23',
      Icon: Mail,
      borderColor: 'border-green-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '39',
    // position: { x: 2500, y: 750 },
    data: {
      label: 'TREASURY',
      text: 'Obtain bank guarantee letter for EscrowAccount opening and mark task as complete',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '24',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '40',
    // position: { x: 1600, y: 980 },
    data: {
      label: 'RERA-DLD',
      text: 'Obtain requireddocuments** for RERA registration & marks the task as complete',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '25',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '41',
    // position: { x: 1900, y: 980 },
    data: {
      label: 'RERA-DLD',
      text: 'Upload RERA certificate & Project Details',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '26',
      Icon: PersonStanding,
      borderColor: 'border-blue-600',
    },
    type: 'rectangle',
  },
  {
    id: '42',
    // position: { x: 3340, y: 960 },
    data: {
      label: 'RERA-DLD',
      text: 'Approval',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '27',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'diamond',
  },
  {
    id: '43',
    // position: { x: 1700, y: 1300 },
    data: {
      label: 'TREASURY',
      text: 'Open the ESCROW account with the bank identified for the Project and mark task as complete',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '28',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '45',
    // position: { x: 1950, y: 1300 },
    data: {
      label: 'FINANCE',
      text: 'Create Account GL Code via API & Autocomplete the task after Account GL is created',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '29',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '46',
    // position: { x: 2200, y: 1300 },
    data: {
      label: 'TREASURY',
      text: 'Raise a SR ticket for Finance APP team to configure Escrow Bank account in Fusion',
      color: 'bg-green-100',
      department: 'planning',
      StepNumber: '30',
      Icon: Mail,
      borderColor: 'border-green-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '47',
    // position: { x: 2500, y: 1300 },
    data: {
      label: 'FINANCE APP',
      text: 'Configure Escrow account in fusion',
      color: 'bg-green-100',
      department: 'planning',
      StepNumber: '31',
      Icon: Mail,
      borderColor: 'border-green-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '48',
    // position: { x: 2750, y: 1300 },
    data: {
      label: 'Treasury',
      text: 'Provide the VA list',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '32',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '49',
    // position: { x: 3000, y: 1300 },
    data: {
      label: 'FINANCE AR',
      text: 'Upload VA in Fusion.Configure DLD & Other charges',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      department: 'planning',
      StepNumber: '33',
    },
    type: 'rectangle',
  },
  {
    id: '50',
    // position: { x: 3250, y: 1300 },
    data: {
      label: 'FINANCE APP',
      text: 'Configure Receipt Methods in fusion',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      department: 'planning',
      StepNumber: '34',
    },
    type: 'rectangle',
  },
  {
    id: '51',
    // position: { x: 3040, y: 1450 },
    data: {
      // label: 'Task is auto-marked ascomplete inPega',
      text: 'Task is auto-marked as complete inPega',
      color: 'bg-blue-200',
      department: 'planning',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'circle',
  },
  {
    id: '52',
    // position: { x: 3600, y: 1290 },
    data: {
      // label: 'FINANCE APP',
      text: 'Task is auto-marked as complete in Pega',
      color: 'bg-blue-200',
      department: 'planning',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'circle',
  },
  {
    id: '53',
    // position: { x: 3290, y: 1550 },
    data: {
      // label: 'FINANCE APP',
      text: 'Finance TEAM Task Ends',
      color: 'bg-red-200',
      department: 'planning',
      borderColor: 'border-red-400',
    },
    type: 'circle',
  },
  {
    id: '54',
    // position: { x: 1700, y: 1650 },
    data: {
      label: 'FINANCE',
      text: 'Create Project GLCode & Autocomplete the taskafter Project GL iscreated',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '35',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '55',
    // position: { x: 2000, y: 1650 },
    data: {
      label: 'FINANCE',
      text: 'Maps the Project GL Code to the inventory and marks the task as complete',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      department: 'planning',
      StepNumber: '36',
    },
    type: 'rectangle',
  },
  {
    id: '56',
    // position: { x: 2450, y: 1650 },
    data: {
      label: 'Treasury',
      text: 'Provide the CVA list',
      color: 'bg-green-100',
      department: 'planning',
      StepNumber: '37',
      Icon: Mail,
      borderColor: 'border-green-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '57',
    // position: { x: 2810, y: 1650 },
    data: {
      label: 'FINANCE AR',
      text: 'Upload CVA inFusion. ConfigureDLD & Other charges',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      department: 'planning',
      StepNumber: '38',
    },
    type: 'rectangle',
  },
  {
    id: '58',
    // position: { x: 2850, y: 1850 },
    data: {
      // label: 'FINANCE AR',
      text: 'Task is auto-marked ascomplete inPega',
      color: 'bg-blue-200',

      department: 'planning',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'circle',
  },
  {
    id: '59',
    // position: { x: 2040, y: 1850 },
    data: {
      // label: 'FINANCE AR',
      text: 'Task is auto-marked as complete in Pega',
      color: 'bg-blue-200',
      department: 'planning',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'circle',
  },
  {
    id: '60',
    // position: { x: 2250, y: 1950 },
    data: {
      label: 'FINANCE APP',
      text: 'Configure Receipt Methods with corporate bank account',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      department: 'planning',
      StepNumber: '39',
    },
    type: 'rectangle',
  },
  {
    id: '61',
    // position: { x: 2280, y: 2080 },
    data: {
      // label: 'FINANCE AR',
      text: 'Task is auto-marked as complete in Pega',
      color: 'bg-blue-200',
      department: 'planning',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
      // StepNumber: '48',
    },
    type: 'circle',
  },
  {
    id: '62',
    // position: { x: 2650, y: 1935 },
    data: {
      // label: 'FINANCE AR',
      text: 'Fin App Task Ends',
      color: 'bg-red-200',
      department: 'planning',
      borderColor: 'border-red-400',
    },
    type: 'circle',
  },
  {
    id: '63',
    // position: { x: 4500, y: 610 },
    data: {
      label: 'SALES ADMIN',
      text: 'Test Booking by releasing Unit',
      color: 'bg-green-100',
      department: 'planning',
      StepNumber: '43',
      borderColor: 'border-green-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '64',
    // position: { x: 5500, y: 610 },
    data: {
      label: 'MID OFFICE',
      text: 'Verify URRF',
      color: 'bg-green-100',
      department: 'planning',
      StepNumber: '44',
      borderColor: 'border-green-600',
    },
    type: 'rectangle',
  },
  {
    id: '65',
    // position: { x: 5500, y: 400 },
    data: {
      text: 'Task is auto-marked as complete in Pega',
      color: 'bg-blue-200',
      department: 'planning',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'circle',
  },
  {
    id: '66',
    // position: { x: 5800, y: 600 },
    data: {
      label: 'SALES OPS HOD',
      text: 'Approval via email',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '46',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'diamond',
  },
  {
    id: '67',
    // position: { x: 6200, y: 650 },
    data: {
      label: 'SALES ADMIN',
      text: 'Cancel Test Booking',
      color: 'bg-green-100',
      borderColor: 'border-green-600',
      department: 'planning',
    },
    type: 'rectangle',
  },
  {
    id: '68',
    // position: { x: 6250, y: 480 },
    data: { 
      text: 'Task is auto-marked ascomplete in Pega',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '48',
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
      Icon: Settings,
    },

    type: 'circle',
  },
  {
    id: '69',
    // position: { x: 6800, y: 640 },
    data: {
      text: 'Booking Launch Ready',
      color: 'bg-red-100',
      department: 'planning',
      borderColor: 'border-red-400',
    },
    type: 'circle',
  },
  {
    id: '70',
    // position: { x: 4500, y: 1000 },
    data: {
      label: 'LEGAL',
      text: 'Confirms Draft SPA creation',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '40',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '71',
    // position: { x: 4500, y: 780 },
    data: {
      label: 'SALESFORCE IT',
      text: 'Uploads draft SPA',
      color: 'bg-green-100',
      department: 'planning',
      StepNumber: '42',
      borderColor: 'border-green-600',
    },
    type: 'rectangle',
  },
  {
    id: '72',
    // position: { x: 4750, y: 1000 },
    data: {
      label: 'CONTRACTS/CDC',
      text: 'Confirms Completion of Draft SPA Validation & Watermark Addition',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '41',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '73',
    // position: { x: 5000, y: 800 },
    data: {
      text: 'Task is auto-marked as complete in Pega',
      color: 'bg-blue-200',
      department: 'planning',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'circle',
  },
  {
    id: '74',
    // position: { x: 5000, y: 1000 },
    data: {
      label: 'SALES ADMIN',
      text: 'Test Booking by releasing Unit',
      color: 'bg-green-100',
      department: 'planning',
      StepNumber: '43',
      borderColor: 'border-green-600',
      // IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '75',
    // position: { x: 5040, y: 1150 },
    data: {
      text: 'Task is auto-marked as complete in Pega',
      color: 'bg-blue-200',
      department: 'planning',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'circle',
  },
  {
    id: '76',
    // position: { x: 5300, y: 1000 },
    data: {
      label: 'MID OFFICE',
      text: 'Verify URRF & SPA in Salesforce',
      color: 'bg-green-100',
      department: 'planning',
      StepNumber: '45',
      borderColor: 'border-green-600',
      // IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '77',
    // position: { x: 5300, y: 800 },
    data: {
      text: 'Task is auto-marked as complete in Pega',
      color: 'bg-blue-200',
      department: 'planning',
      Icon: Settings,
      // StepNumber: '48',
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'circle',
  },
  {
    id: '78',
    // position: { x: 5600, y: 1000 },
    data: {
      label: 'SALES OPS HOD',
      text: 'Approval via email',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '46',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'diamond',
  },
  {
    id: '79',
    // position: { x: 6000, y: 1000 },
    data: {
      label: 'LEGAL HOD',
      text: 'Approval on test SPA',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '47',
      Icon: Mail,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'diamond',
  },
  {
    id: '80',
    // position: { x: 6500, y: 1030 },
    data: {
      label: 'SALES ADMIN',
      text: 'Cancel Test Booking',
      color: 'bg-green-100',
      department: 'planning',
      borderColor: 'border-green-600',
      // IconColor: 'text-yellow-600',
    },
    type: 'rectangle',
  },
  {
    id: '81',
    // position: { x: 6540, y: 1200 },
    data: {
      text: 'Task is auto-marked as complete in Pega',
      color: 'bg-blue-200',
      department: 'planning',
      StepNumber: '48',
      Icon: Settings,
      borderColor: 'border-blue-600',
      IconColor: 'text-blue-600',
    },
    type: 'circle',
  },
  {
    id: '82',
    // position: { x: 7200, y: 950 },
    data: {
      text: 'SPA & Booking Launch Ready',
      color: 'bg-red-200',
      department: 'planning',
      borderColor: 'border-red-400',
      // IconColor: 'text-yellow-600',
    },
    type: 'circle',
  },
  {
    id: '83',
    // position: { x: 8500, y: 1550 },
    data: {
      text: 'Ready to Accept Bookings',
      color: 'bg-orange-400',
      borderColor: 'border-orange-600',
      department: 'planning',
      // IconColor: 'text-yellow-600',
    },
    type: 'circle',
  },
];
